/**
 * Tool 2: explain_medication
 *
 * Zoom in on one drug and return the full "why is this patient on this?"
 * answer. This is the tool you'd call when a patient asks "what's this
 * pill for?" and the clinician needs a grounded answer in 2 seconds.
 *
 * Repetitive task: answering patient med questions.
 */

import type { SharpContext } from "../sharp.js";
import {
  fetchActiveMedications,
  resolveConditions,
} from "../fhir/medications.js";
import { enrichDrug } from "../enrich/rxnav.js";

export async function explainMedication(
  ctx: SharpContext,
  medicationFhirId: string
) {
  const meds = await fetchActiveMedications(ctx);
  const target = meds.find((m) => m.fhirId === medicationFhirId);

  if (!target) {
    return {
      error: `Medication ${medicationFhirId} not found in active list for this patient.`,
    };
  }

  const conditionMap = await resolveConditions(ctx, target.reasonRefs);
  const enrichment = target.rxnormCode
    ? await enrichDrug(target.rxnormCode, target.name)
    : null;

  const whyFromRefs = target.reasonRefs
    .map((ref) => conditionMap[ref])
    .filter(Boolean);
  const why = [...whyFromRefs, ...target.reasonTexts];

  return {
    medication: {
      name: target.name,
      dosage: target.dosage,
      authoredOn: target.authoredOn,
      source: target.source,
      fhirId: target.fhirId,
    },
    reasonForUse: why.length > 0 ? why : ["(no reason recorded in chart)"],
    drugInfo: enrichment
      ? {
          genericName: enrichment.genericName,
          brandNames: enrichment.brandNames,
          therapeuticClasses: enrichment.therapeuticClasses,
          infoSource:
            "NIH RxNav / RxClass — https://rxnav.nlm.nih.gov",
        }
      : null,
    footer:
      "Generated by Scrub. Drug information sourced from NIH public APIs. Clinician review required.",
  };
}
