/**
 * Tool 3: find_recent_changes
 *
 * Returns medications that were added, modified, or stopped in the last
 * N days. Purely mechanical — no "smart" anomaly detection, just a diff.
 * Let the clinician decide what's weird; your job is to surface the delta.
 *
 * Repetitive task: scanning through records to figure out "what's new
 * since last time I saw this patient."
 */

import type { SharpContext } from "../sharp.js";
import { fhirSearch } from "../fhir/client.js";

export async function findRecentChanges(
  ctx: SharpContext,
  days: number = 90
) {
  const cutoff = new Date();
  cutoff.setDate(cutoff.getDate() - days);
  const cutoffIso = cutoff.toISOString().split("T")[0];

  // Active meds authored in the window = newly started or changed
  const recentActive = await fhirSearch<any>(
    ctx,
    `/MedicationRequest?patient=${ctx.patientId}&authoredon=ge${cutoffIso}&_count=100`
  );

  // Stopped/completed meds in the window = discontinued
  const recentStopped = await fhirSearch<any>(
    ctx,
    `/MedicationRequest?patient=${ctx.patientId}&status=stopped,completed&authoredon=ge${cutoffIso}&_count=100`
  );

  const started = recentActive
    .filter((r: any) => r.status === "active")
    .map((r: any) => ({
      name:
        r.medicationCodeableConcept?.text ??
        r.medicationCodeableConcept?.coding?.[0]?.display ??
        "unknown",
      authoredOn: r.authoredOn,
      status: r.status,
      fhirId: r.id,
    }));

  const stopped = recentStopped.map((r: any) => ({
    name:
      r.medicationCodeableConcept?.text ??
      r.medicationCodeableConcept?.coding?.[0]?.display ??
      "unknown",
    authoredOn: r.authoredOn,
    status: r.status,
    fhirId: r.id,
  }));

  return {
    patientId: ctx.patientId,
    windowDays: days,
    cutoffDate: cutoffIso,
    started: {
      count: started.length,
      items: started,
    },
    stopped: {
      count: stopped.length,
      items: stopped,
    },
    footer:
      "Generated by Scrub. Raw diff of MedicationRequest activity in the window. Clinician review required.",
  };
}
