/**
 * Tool 1: get_patient_med_context
 *
 * The main tool. Takes a patient, returns a one-page-style document with
 * every active medication enriched with: why (linked condition), who
 * (prescriber), when (authored date), and what it actually is (RxNav
 * generic/brand/class).
 *
 * This is the "repetitive task" your mom described — assembling scattered
 * chart info into one place.
 */

import type { SharpContext } from "../sharp.js";
import {
  fetchActiveMedications,
  resolveConditions,
} from "../fhir/medications.js";
import { enrichDrug } from "../enrich/rxnav.js";
import {
  renderMedContextDocument,
  type PatientMedContextData,
} from "../format/document.js";

export type { PatientMedContextData };

export async function getPatientMedContext(
  ctx: SharpContext,
  options?: { format?: "json" | "markdown" }
): Promise<PatientMedContextData | string> {
  const meds = await fetchActiveMedications(ctx);

  // Collect all condition refs across all meds and resolve them in one pass
  const allConditionRefs = [...new Set(meds.flatMap((m) => m.reasonRefs))];
  const conditionMap = await resolveConditions(ctx, allConditionRefs);

  // Enrich each drug with RxNav info in parallel
  const enrichments = await Promise.all(
    meds.map((m) => (m.rxnormCode ? enrichDrug(m.rxnormCode, m.name) : null))
  );

  const items = meds.map((m, i) => {
    const enrichment = enrichments[i];
    const whyFromRefs = m.reasonRefs
      .map((ref) => conditionMap[ref])
      .filter(Boolean);
    const why = [...whyFromRefs, ...m.reasonTexts];

    return {
      name: m.name,
      dosage: m.dosage ?? "(no dosage recorded)",
      authoredOn: m.authoredOn ?? "(unknown)",
      why: why.length > 0 ? why : ["(no reason recorded in chart)"],
      enrichment: enrichment
        ? {
            genericName: enrichment.genericName ?? "(unknown)",
            brandNames: enrichment.brandNames,
            therapeuticClasses: enrichment.therapeuticClasses,
          }
        : null,
      source: m.source,
      fhirId: m.fhirId,
    };
  });

  const data: PatientMedContextData = {
    patientId: ctx.patientId,
    generatedAt: new Date().toISOString(),
    medicationCount: items.length,
    medications: items,
    footer:
      "Generated by Scrub from FHIR resources. Findings are advisory. Clinician review required.",
  };

  const format = options?.format ?? "json";
  if (format === "markdown") {
    return renderMedContextDocument(data);
  }
  return data;
}